### ISSUE TITLE
InventoryDragEvent is not handled/cancelled

### ISSUE THREAD

**Issue by Phoenix616** [DRE2N/Vignette#1]
The listener currently does not seem to handle or cancel the InventoryDragEvent. This could lead to cases where a player could insert (and loose) items into the GUI or even extracting them as dragging of an item (even for a single pixel!) does not call a click event anymore but a drag event. The best solution imo. would be to just cancel it and handle it as if it was clicked if only one item was dragged. (This would allow accidental drags that are meant to be clicks but resulted in slight mouse movement to still be counted as clicks)

**Comment by Sataniel98** [comment]
Thanks for the report, I wasn't aware of that.

BTW, how did you find this project? ^^

**Comment by Phoenix616** [comment]
Via DungeonsXL :)
